baseURL = "https://ikaz.uk/"
languageCode = "ja-jp"
title = "ikazuk's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "ikazuk"
  description = "Test (description)"
  github = "Ichinose-Kazuki"
  # facebook = "Test (facebook)"
  twitter = "kazukiichinose"
  linkedin = "Test (linkedin)"
  # instagram = "Test (instagram)"
  # tumblr = "Test (tumblr)"
  email = "Test (email)"
  url = "https://ikaz.uk"
  keywords = "blog, Test (keywords)"
  rss = true
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "/images/aiavatar.png"
  headerIcon = "/images/github-mark-white.png"
  location = "Japan"
  userStatusEmoji = "ğŸ˜€"
  enableGitalk = true

  [params.gitalk]
    clientID = "Your client ID" # Your client ID
    clientSecret = "Your client secret" # Your client secret
    repo = "LuvSia" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "ventusoon" # æ‚¨çš„GitHub ID
    admin = "ventusoon" # æ‚¨çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.
  # [[params.links]]
  #   title = "Link"
  #   href = "https://github.com/Ichinose-Kazuki"
  # [[params.links]]
  #   title = "Link2"
  #   href = "https://ikaz.uk"
  #   icon = "https://ikaz.uk/images/aiavatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "Test (google analytics)"
